import React,{useState}from'react';import{Building2,Store,UserRoundCheck,Users,ArrowLeft,Eye,EyeOff}from'lucide-react';
const accounts=[['Pusat','Portal kantor pusat',Building2],['Cabang','Portal kantor cabang',Store],['Agen','Portal agen',UserRoundCheck],['Jamaah','Portal jamaah',Users]];
export default function App(){const[screen,setScreen]=useState('choose');const[role,setRole]=useState(null);const[show,setShow]=useState(false);
const selectRole=(r)=>{setRole(r);setScreen('login')};
return <main className="shell"><section className="card">
{screen!=='choose'&&<button className="back" onClick={()=>setScreen(screen==='register'?'login':'choose')}><ArrowLeft/></button>}
<div className="brand"><div className="logo-mark">الفوزي</div><h1>AL FAUZI TOUR</h1><p>UMRAH & HAJI</p></div>
{screen==='choose'&&<><h2>Bismillahirrohmaanirrohiim</h2><h3>Assalamu'alaykum</h3><p className="lead">Pilih tipe akun untuk melanjutkan</p><div className="roles">{accounts.map(([name,desc,Icon])=><button key={name} className="role" onClick={()=>selectRole(name)}><Icon/><b>{name}</b><span>{desc}</span></button>)}</div></>}
{screen==='login'&&<><div className="portal-tag">{role}</div><h2>Masuk ke Portal</h2><p className="lead">Gunakan akun {role?.toLowerCase()} Anda</p><form onSubmit={e=>e.preventDefault()}><label>Email<input type="email" placeholder="nama@email.com"/></label><label>Password<div className="password"><input type={show?'text':'password'} placeholder="Masukkan password"/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff/>:<Eye/>}</button></div></label><div className="row"><label className="remember"><input type="checkbox"/> Ingat saya</label><a href="#">Lupa password</a></div><button className="primary">Masuk</button></form><p className="switch">Belum punya akun? <button onClick={()=>setScreen('register')}>Daftar Sekarang</button></p></>}
{screen==='register'&&<><div className="portal-tag">{role}</div><h2>Buat akun baru</h2><p className="lead">Mulai dari satu tujuan yang bermakna.</p><form onSubmit={e=>e.preventDefault()}><label>Nama lengkap<input placeholder="Nama lengkap"/></label><label>No. WhatsApp<input placeholder="Contoh: 081234567890"/></label><label>Email<input type="email" placeholder="nama@email.com"/></label><label>Password<div className="password"><input type={show?'text':'password'}/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff/>:<Eye/>}</button></div></label><label>Konfirmasi password<input type="password"/></label><label className="remember"><input type="checkbox"/> Ingat saya</label><button className="primary">Daftar</button></form><p className="switch">Sudah punya akun? <button onClick={()=>setScreen('login')}>Masuk</button></p></>}
<footer>Developed by Markaz Dakwah Digital</footer></section></main>}